common/models/Bot.php
<?php
/**
 * @link http://www.noghteh.ir/
 * @copyright Copyright (c) 2015 Noghteh
 * @license http://www.noghteh.ir/license/
 */

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use airani\telegram\TelegramBot;
use yii\helpers\Json;

/**
 * This is the model class for table "{{%bot}}".
 *
 * @property integer $bot_id
 * @property string $name
 * @property string $username
 * @property string $token
 * @property string $owner
 * @property integer $channel_id
 * @property integer $userOwnerId
 *
 * @property Channel $channel
 *
 * @author Ali Irani <ali@irani.im>
 */
class Bot extends ActiveRecord
{
    public $projectId;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%bot}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['token', 'required'],
            ['token', 'match', 'pattern' => '/\d+\:.*/i'],
            ['token', 'validateToken'],
            [['token', 'username'], 'unique'],
            [['token', 'owner'], 'string', 'max' => 128],
            ['bot_id', 'unique'],
            //['owners', 'each', 'rule' => ['match', 'pattern' => '/@/', 'not' => true, 'message' => Yii::t('app', '@ is not valid!')]],
            ['owners', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'bot_id' => Yii::t('app', 'Bot ID'),
            'name' => Yii::t('app', 'Name'),
            'username' => Yii::t('app', 'Username'),
            'token' => Yii::t('app', 'Token'),
            'owner' => Yii::t('app', 'Owner'),
            'owners' => Yii::t('app', 'Owners'),
            'channel_id' => Yii::t('app', 'Channel ID'),
            'groupsCount' => Yii::t('app', 'Group Count'),
            'channel.project.name' => Yii::t('app', 'Project Name'),
        ];
    }

    /**
     * @inheritDoc
     */
    public function init()
    {
        parent::init();

        $this->on(self::EVENT_BEFORE_INSERT, [$this, 'setBotAttributes']);
        $this->on(self::EVENT_BEFORE_UPDATE, [$this, 'setBotAttributes']);

        $this->on(self::EVENT_BEFORE_INSERT, [$this, 'setChannelId']);

        $this->on(self::EVENT_AFTER_INSERT, [$this, 'setWebhook']);
        $this->on(self::EVENT_AFTER_UPDATE, [$this, 'setWebhook']);

        $this->on(self::EVENT_AFTER_DELETE, [$this, 'unsetWebhook']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannel()
    {
        return $this->hasOne(Channel::className(), ['id' => 'channel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChats()
    {
        return $this->hasMany(Chat::className(), ['member_id' => 'member_id'])->viaTable('{{%channel_member}}', ['channel_id' => 'channel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroups()
    {
        return $this->hasMany(Group::className(), ['channel_id' => 'channel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupsCount()
    {
        return $this->getGroups()->count();
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActiveChats()
    {
        return $this->hasMany(Chat::className(), ['member_id' => 'member_id'])
            ->viaTable('{{%channel_member}}', ['channel_id' => 'channel_id'], function ($query) {
            /* @var $query \yii\db\ActiveQuery */
            return $query->andWhere(['status' => ChannelMember::STATUS_ACTIVE]);
        });
    }

    /**
     * Returns user owner id
     * @return int|null
     */
    public function getUserOwnerId()
    {
        /* @var ProjectUser $projectUser */
        $project_id = $this->channel->project_id;
        $projectUser = ProjectUser::findOne(['project_id' => $project_id, 'role' => ProjectUser::ROLE_OWNER]);
        return $projectUser ? $projectUser->user_id : null;
    }

    /**
     * @inheritdoc
     * @return BotQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BotQuery(get_called_class());
    }

    /**
     * Return model with active status
     * @param $id
     * @return array|Bot|null
     */
    public static function findActiveOne($id)
    {
        return static::find()->joinWith('channel')->where(['id' => $id, '{{%channel}}.status' => Channel::STATUS_ACTIVE])->one();
    }

    /**
     * Validate telegram bot token
     * @return bool
     */
    public function validateToken()
    {
        $bot = $this->getBotInfo();

        if (isset($bot->ok) === false) {
            $this->addError('connection', Yii::t('app', 'Connection is timeout, Please try again.'));
            Yii::warning(['error' => 'Telegram connection is timeout.', 'botToken' => $bot->token], __METHOD__);
            return false;
        } elseif ($bot->ok == false) {
            $this->addError('token', Yii::t('app', 'Token is invalid!'));
            return false;
        }

        return true;
    }

    /**
     * Return bot owners in array
     * @return array
     */
    public function getOwners()
    {
        $owners = json_decode($this->owner);
        return is_array($owners) ? $owners : [];
    }

    /**
     * Set bot owners with Json format in owner field
     * @param array $items Owners username
     */
    public function setOwners($items)
    {
        $this->owner = is_array($items) ? Json::encode($items) : '';
    }

    /**
     * Returns bot information
     * @return mixed
     */
    public function getBotInfo()
    {
        $bot = new TelegramBot(['authKey' => $this->token]);
        return $bot->getMe();
    }

    /**
     * Returns webhook url
     * @return mixed
     */
    public function getWebhookUrl()
    {
        $tokens = explode(':', $this->token);
        $urlManager = Yii::$app->urlManagerService;

        return $urlManager->createAbsoluteUrl([
            'api/hook',
            'tokenId' => $tokens[0],
            'tokenString' => $tokens[1]
        ], 'https');
    }

    /**
     * Set webhook url for bot
     * @return bool
     */
    public function setWebhook($webhook = null)
    {
        $webhook = $webhook === null ? $webhook : $this->webhookUrl;
        $telegram = new TelegramBot(['authKey' => $this->token]);
        $response = $telegram->setWebhook($webhook);

        return isset($response->ok) ? $response->ok : false;
    }

    /**
     * Unset bot webhook
     * @return bool
     */
    public function unsetWebhook()
    {
        return $this->setWebhook('');
    }

    /**
     * Get bot info and set to attributes
     * @return bool
     */
    public function setBotAttributes()
    {
        if (isset($this->botInfo->result) === false || !($bot = $this->botInfo->result)) {
            return false;
        }

        $this->setAttributes([
            'bot_id' => $bot->id,
            'name' => $bot->first_name,
            'username' => $bot->username,
        ], false);

        return true;
    }

    /**
     * Add channel record and set channel_id
     * @return bool
     */
    public function setChannelId()
    {
        if ($this->bot_id === null) {
            return false;
        }

        $channel = new Channel([
            'project_id' => $this->projectId,
            'type' => Channel::TYPE_TELEGRAM_BOT,
        ]);

        if ($channel->save()) {
            $this->channel_id = $channel->id;
            return true;
        }

        return false;
    }
}

backend/controllers/BotController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Bot;
use backend\models\BotSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BotController implements the CRUD actions for Bot model.
 */
class BotController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['superAdmin'],
                    ],
                ],
            ]
        ];
    }

    /**
     * Lists all Bot models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BotSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Bot model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Bot model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Bot();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->channel_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Bot model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->channel_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Bot model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Bot model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Bot the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bot::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/BotController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use common\models\Channel;
use common\models\Bot;

/**
 * BotController implements the CRUD actions for Bot model.
 */
class BotController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['updateProject'],
                        'actions' => ['create', 'update', 'view'],
                    ],
                ],
            ]
        ];
    }

    /**
     * Displays a single Bot model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $project_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'projectId' => $project_id,
        ]);
    }

    /**
     * Creates a new Bot model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $project_id
     * @return mixed
     */
    public function actionCreate($project_id)
    {
        /* @var Bot $model */
        /* @var Bot $bot */
        /* @var Channel $channel */
        $model = new Bot(['projectId' => $project_id]);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->setBotAttributes() && $model->save()) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ['success' => true];
                }
                return $this->redirect(['view', 'id' => $model->channel_id, 'project_id' => $project_id]);
            } elseif (($bot = Bot::findOne(['bot_id' => $model->bot_id])) && ($channel = Channel::findOne(['id' => $bot->channel_id, 'status' => Channel::STATUS_DELETED]))) {
                $channel->project_id = $project_id;
                $channel->status = Channel::STATUS_ACTIVE;
                if ($channel->update()) {
                    if (Yii::$app->request->isAjax) {
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return ['success' => true];
                    }
                    return $this->redirect(['view', 'id' => $channel->id, 'project_id' => $project_id]);
                }
            }
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ['success' => false, 'errors' => $model->errors];
            }
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('_form', [
                'model' => $model,
                'projectId' => $project_id,
            ]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'projectId' => $project_id,
            ]);
        }
    }

    /**
     * Updates an existing Bot model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $project_id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ['success' => true];
                }
                return $this->redirect(['view', 'id' => $model->channel_id, 'project_id' => $project_id]);
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['success' => false, 'errors' => $model->errors];
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('_form', [
                'model' => $model,
                'projectId' => $project_id,
            ]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'projectId' => $project_id,
            ]);
        }
    }

    /**
     * Finds the Bot model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Bot the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bot::findActiveOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
    }
}

frontend/views/bot/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model common\models\Bot */
/* @var $form yii\widgets\ActiveForm */
/* @var $projectId */

$action = $model->isNewRecord ? Url::to(["bot/create", 'project_id' => $projectId]) : Url::to(["bot/update", 'id' => $model->channel_id, 'project_id' => $projectId]);
?>

<div class="bot-form">

    <?php $form = ActiveForm::begin(['action' => $action, 'options' => ['id'=>'ajaxForm']]); ?>

    <?= $form->field($model, 'token')->textInput(['maxlength' => true, 'dir' => 'ltr'])
        ->hint(Yii::t('app', 'What is security token? How to create a bot on Telegram?') . ' ' . Html::a(Yii::t('app', 'See Here'), 'https://core.telegram.org/bots#3-how-do-i-create-a-bot')) ?>
    <?= $form->field($model, 'owners')->widget(Select2::className(), [
        'showToggleAll' => false,
        'options' => [
            'placeholder' => Yii::t('app', 'Enter owner usernames ...'),
            'multiple' => true
        ],
        'pluginOptions' => [
            'tags' => true,
        ],
    ])->hint(Yii::t('app', "Enter usernames of bot owners in Telegram")); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/bot/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Bot */

$this->title = Yii::t('app', 'Create Bot');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Channels'), 'url' => ['channel/index', 'project_id' => $model->projectId]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bot-create box box-primary">

    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
            'projectId' => $projectId,
        ]) ?>
    </div>

</div>

frontend/views/bot/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Bot */
/* @var $projectId */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => Yii::t('app', 'Bot'),
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Channels'), 'url' => ['channel/index', 'project_id' => $projectId]];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->channel_id, 'project_id' => $projectId]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="bot-update box box-primary">

    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
            'projectId' => $projectId,
        ]) ?>
    </div>

</div>

frontend/views/bot/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Bot */
/* @var $projectId */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Channels'), 'url' => ['channel/index', 'project_id' => $projectId]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bot-view box box-primary">

    <div class="box-body">
        <?php if (Yii::$app->user->can('updateProject')) : ?>
        <p>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->channel_id, 'project_id' => $projectId], [
                'class' => 'showModalButton btn btn-primary',
                'onclick' => 'return false;',
                'data' => [
                    'url' => Url::to(['update', 'id' => $model->channel_id, 'project_id' => $projectId]),
                ]
            ]); ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['channel/delete', 'id' => $model->channel_id, 'project_id' => $projectId], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
        <?php endif; ?>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'name',
                [
                    'attribute' => 'username',
                    'value' => Html::a('@' . $model->username, 'https://telegram.me/' . $model->username),
                    'format' => 'html'
                ],
                [
                    'label' => Yii::t('app', 'Owners'),
                    'attribute' => 'owner',
                    'value' => implode(', ', Json::decode($model->owner)),
                ],
                'channel.created_at:todayTime',
            ],
        ]) ?>
    </div>

</div>